### ISSUE TITLE
Add hint option

### ISSUE THREAD

**Issue by kaal-coder** [CareerDevelopmentHub/Sudoku-Solver#5]
When clicked on hint, the user would get solutions of 2 blank spaces from the board.

**Comment by smashcoder** [comment]
Hey, I am interested in this. Can you assign this issue to me ?

**Comment by kaal-coder** [comment]
Yeah sure. Send a preview of changes you made before making a PR.

**Comment by smashcoder** [comment]
Okay, I will share you the screenshot once the chances are being done.

**Comment by kaal-coder** [comment]
@smashcoder you working on it ?

**Comment by smashcoder** [comment]
Ya, I am on it.

**Comment by kaal-coder** [comment]
Great then, expecting you to complete by tomorrow

**Comment by smashcoder** [comment]
I will need some time as I am working with a multiple projects and handling my college sessions too. I will update you within 2-3 days.

**Comment by kaal-coder** [comment]
@smashcoder okay

**Comment by smashcoder** [comment]
I am facing 2-3 issues while developing a code for the button.

Issue 1 : CSS File
I am unable to find the css that has being used for buttons. If you have imported it from other source please provide me the resource.
Issue 2 : Solve Button Functioning
How does the solve button works ? Please explain it's working so that in the same way the hint button should also work.
Issue 3 : Creating A Pull Request
Should I create a pull request till the work I have done or send my work in a new branch of this repository ? ( Even thou you might feel no need for such small change pull request but keeping a backup by branching would not only keep Hint button setting same but also help you and other people know there are other things that are going to add up)

**Comment by smashcoder** [comment]
Please Let Me Know what should I do regarding the changes that I had shared with you?
